name: Metrics

on:
  # Lên lịch cập nhật hàng ngày
  schedule:
    - cron: "0 0 * * *"
  # (tùy chọn) Chạy workflow bằng tay
  workflow_dispatch:
  # (tùy chọn) Chạy workflow khi đẩy lên master/main
  push:
    branches:
      - "master"
      - "main"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Generate Isocalendar Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          config_timezone: Asia/Bangkok
          filename: metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes

      
